### ISSUE TITLE
Compiler error on Mac

### ISSUE THREAD

**Issue by mesut-guenes** [des-testbed/libara#17]
I cannot compile the package on my Mac. I get the following error:

Compiling .//core/AbstractARAClient.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make[1]: *** [../out/gcc-debug/libara/.//core/AbstractARAClient.o] Error 1
make: *** [arasource] Error 2

It seems that you require c++11 which is maybe not supported by all GCC versions?

**Comment by mfrey** [comment]
I close this issue since both, the used MacOSX version and the compiler are outdated.
